blog/urls.py
from django.urls import path

from blog.views import (
    IndexView,
    PostDetailView,
    CategoryListView,
    CategoryPostView,
    TagListView,
    TagPostView,
    SearchPostView,
    CommentFormView,
    comment_approve,
    comment_remove,
    ReplyFormView,
    reply_approve,
    reply_remove,
)

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
    path('comment/<int:pk>/', CommentFormView.as_view(), name='comment_form'),
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    path('reply/<int:pk>/', ReplyFormView.as_view(), name='reply_form'),
    path('reply/<int:pk>/approve/', reply_approve, name='reply_approve'),
    path('reply/<int:pk>/remove/', reply_remove, name='reply_remove'),
]

dbsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name





class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    description = models.TextField(blank=True)
    image = models.ImageField(
        upload_to='post_images/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class ContentImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text




class Reply(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='replies')
    author = models.CharField(max_length=50)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

  

blog/forms.py
from django.forms import ModelForm, TextInput, Textarea

from blog.models import Comment, Reply


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Name',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Contents',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }


class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ('author', 'text')
        widgets = {
            'author': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Name',
            }),
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Reply',
            }),
        }
        labels = {
            'author': '',
            'text': '',
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from blog.forms import CommentForm, ReplyForm
from blog.models import Post, Category, Tag, Comment, Reply


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 3


class CategoryPostView(ListView):
    model = Post
    template_name = 'blog/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class TagPostView(ListView):
    model = Post
    template_name = 'blog/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context


class SearchPostView(ListView):
    model = Post
    template_name = 'blog/search_post.html'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(category__name__icontains=query) |
            Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))


class CommentFormView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('blog:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        context['post'] = get_object_or_404(Post, pk=post_pk)
        return context


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)


class ReplyFormView(CreateView):
    model = Reply
    form_class = ReplyForm

    def form_valid(self, form):
        reply = form.save(commit=False)
        comment_pk = self.kwargs['pk']
        reply.comment = get_object_or_404(Comment, pk=comment_pk)
        reply.save()
        return redirect('blog:post_detail', pk=reply.comment.post.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        context['comment'] = get_object_or_404(Comment, pk=comment_pk)
        return context


@login_required
def reply_approve(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.approve()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)


@login_required
def reply_remove(request, pk):
    reply = get_object_or_404(Reply, pk=pk)
    reply.delete()
    return redirect('blog:post_detail', pk=reply.comment.post.pk)

blog/templates/blog/category_list.html
{% extends "base.html" %}

{% block title %}Categories's list | {{ block.super }}{% endblock %}
{% block description %}Categories's list{% endblock %}

{% block content %}
<h1>Categories's list</h1>
<ul>
  {% for category in object_list %}
  <li><a href="{% url 'blog:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a></li>
  {% empty %}
  <li>No categories</li>
  {% endfor %}
</ul>
{% endblock %}

blog/templates/blog/category_post.html
{% extends "base.html" %}

{% block title %}{{ category.name }} | {{ block.super }}{% endblock %}
{% block description %}「{{ category.name }}」's posts{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">「{{ category.name }}」's post</h1>
      {% include "blog/snippets/main_post_list.html" %}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "base.html" %}

{% block title %}Comment | {{ block.super }}{% endblock %}
{% block description %} Comment form。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">comment form</h1>
      <p>To:「{{ post.title }}」</p>
      <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">send</button>
      </form>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block title %}Post's list | {{ block.super }}{% endblock %}
{% block description %} My blog。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">List</h1>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination.html" %}
      {# {% include "blog/snippets/pagination_b.html" %} #}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }} | {{ block.super }}{% endblock %}
{% block description %}{{ object.description }}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <article class="blog-area">
        <h1>{{ object.title }}</h1>
        <p>{{ object.published_at|date }}</p>
        <p>{{ object.category.name }}</p>
        {% for tag in object.tags.all %}
        {{ tag.name }}
        {% endfor %}
        <hr>
        {{ object.content|safe }}
      </article>
      <article class="comment-area">
        <a class="btn btn-primary my-3" href="{% url 'blog:comment_form' post.pk %}">Comment</a>
        {% include "blog/snippets/comments.html" %}
      </article>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/reply_form.html
{% extends "base.html" %}

{% block title %} Commrent form | {{ block.super }}{% endblock %}
{% block description %}Comment{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">comment form</h1>
      <p>To: {{ comment.author }}</p>
      <p class="text-black-50">{{ comment.text|linebreaksbr }}</p>
      <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">send</button>
      </form>
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/search_post.html
{% extends "base.html" %}

{% block title %}{% if query %}{{ query }}{% endif %} | {{ block.super }}{% endblock %}
{% block description %}Search「{% if query %}{{ query }}{% endif %}」result{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">「{% if query %}{{ query }}{% endif %}」's results</h1>
      <p class="text-right">{{ page_obj.start_index }}-{{ page_obj.end_index }}（{{ paginator.count }}件）</p>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination.html" %}
      {# {% include "blog/snippets/pagination_b.html" %} #}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

blog/templates/blog/tag_list.html
{% extends "base.html" %}

{% block title %}Tag list | {{ block.super }}{% endblock %}
{% block description %}Tag list{% endblock %}

{% block content %}
<h1>Tag list</h1>
<ul>
  {% for tag in object_list %}
  <li><a href="{% url 'blog:tag_post' tag.slug %}">{{ tag.name }} ({{ tag.num_posts }})</a></li>
  {% empty %}
  <li>No tags</li>
  {% endfor %}
</ul>
{% endblock %}

blog/templates/blog/tag_post.html
{% extends "base.html" %}

{% block title %}#{{ tag.name }} | {{ block.super }}{% endblock %}
{% block description %}「{{ tag.name }}」posts{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">「#{{ tag.name }}」's posts</h1>
      {% include "blog/snippets/main_post_list.html" %}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}